CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_attention_detector_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_attention_detector_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_attention_detector_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_attention_detector_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_attention_detector_3classes_uniform_init.py
