CUDA_VISIBLE_DEVICES=4 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_base_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=4 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_base_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=4 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_base_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=4 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_base_3classes_uniform_init.py
CUDA_VISIBLE_DEVICES=4 python tools/train.py configs/faster_rcnn/logo_faster_rcnn_r50_fpn_1x_coco_base_3classes_uniform_init.py
